site_name: Red Team 101


# appearance info
theme:

  name: material
  
  ##colorscheme
  palette:

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to system preference

  font:
    text: Roboto
    code: Fira Code

  language: en

  icon:
    logo: material/library
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  ##navigation
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    # - toc.follow
    - navigation.top
    - header.autohide
    ##plugin: search
    - search.suggest
    - search.highlight
    - search.share
    ##markdown extension
    - content.code.copy
    - content.code.copy
    - content.code.annotate


# content navigation
nav:
  - Home:
    - index.md
  - Linux:
    - Linux/index.md
    - Regular Expression: Linux/regexp.md
    - Manipulate Text:
      - grep: Linux/manipulate_text/grep.md
      - sed: Linux/manipulate_text/sed.md
      - awk: Linux/manipulate_text/awk.md
      - cut: Linux/manipulate_text/cut.md
      - tr: Linux/manipulate_text/tr.md
    - Shell:
      - Linux/shell/index.md
  - Crypto:
    - Crypto/index.md
    - Generate Password: Crypto/gen_passwd.md
  - Reverse Engineering:
    - RE/index.md
    - Programming Languages:
      - C Programming: RE/langs/C.md
      - C++ Programming: RE/langs/C++.md
  - Pentest:
    - Pentest/index.md
    - Reconnaissance:
      - Pentest/1.recon/index.md
      - Web: Pentest/1.recon/web.md
      - Path: Pentest/1.recon/path.md
      - OS: Pentest/1.recon/os.md
      - SMB: Pentest/1.recon/smb.md
      - DNS: Pentest/1.recon/dns.md
      - CDN: Pentest/1.recon/cdn.md
      - WAF: Pentest/1.recon/waf.md
      - Asset: Pentest/1.recon/asset.md
      - Web Source Code: Pentest/1.recon/web_source_code.md
      - Website Info: Pentest/1.recon/website_info.md
    - Quick Server:
      - Pentest/3.quick_server/index.md
    - Better Shell:
      - Pentest/2.0.better_shell/index.md
    - Reverse Shell:
      - Pentest/2.rshell/index.md
      - Detail of bash rshell: Pentest/2.rshell/detail_of_bash_rshell.md
    - Services:
      - Pentest/4.services/index.md
    - Vulnerabilities:
      - Pentest/5.vulns/index.md
    - Priviledge Escalation:
      - Pentest/6.priviledge_escalation/index.md
      - Linux:
        - enumeration: Pentest/6.priviledge_escalation/linux/1.enumeration.md
        - shadow: Pentest/6.priviledge_escalation/linux/2.shadow.md
        - passwd: Pentest/6.priviledge_escalation/linux/3.passwd.md
        - sudo environment variables: Pentest/6.priviledge_escalation/linux/4.sudo_env_vars.md
        - schedule tasks: Pentest/6.priviledge_escalation/linux/5.schedule_jobs.md
        - suid: Pentest/6.priviledge_escalation/linux/6.suid.md
        - password and keys: Pentest/6.priviledge_escalation/linux/7.password_and_keys.md
        - nfs: Pentest/6.priviledge_escalation/linux/8.nfs.md
        - kernel exploits: Pentest/6.priviledge_escalation/linux/9.kernel_exploits.md
        - doas related: Pentest/6.priviledge_escalation/linux/10.doas.md
        - motd mechanism: Pentest/6.priviledge_escalation/linux/11.motd_mechanism.md
        - prng for ssh private key: Pentest/6.priviledge_escalation/linux/12.prng_for_ssh.md
      - Linux Sudo Cmds: Pentest/6.priviledge_escalation/linux_sudo.md
      #- Windows:
  - Writeups:
    - Write-ups/index.md
    - Network Config: Write-ups/vulnhub/network-config.md
    - HackTheBox:
      - Starting Point:
        - Write-ups/thb/starting_point/Archetype.md
        - Write-ups/thb/starting_point/Oopsie.md
        - Write-ups/thb/starting_point/Vaccine.md
        - Write-ups/thb/starting_point/Unified.md
      - Linux Boxes:
        - Write-ups/thb/linux/Lame.md
        - Brainfuck (Insane): Write-ups/thb/linux/Brainfuck.md
        - Write-ups/thb/linux/Shocker.md
        - Write-ups/thb/linux/Bashed.md
        - Write-ups/thb/linux/Nibbles.md
      - Open Beta Season III:
        - Write-ups/thb/active_machines/Keeper.md
        - Write-ups/thb/active_machines/Clicker.md
        - Write-ups/thb/active_machines/Zipping.md
        - Drive (Hard): Write-ups/thb/active_machines/Drive.md
        - Devvortex: Write-ups/thb/active_machines/Devvortex.md
        - Write-ups/thb/active_machines/Sau.md
        - Write-ups/thb/active_machines/CozyHosting.md
        - Cybermonday (Hard): Write-ups/thb/active_machines/Cybermonday.md
    - VulnHub:
      - Previous Versions:
        - Kioptrix Level 1 (1): Write-ups/vulnhub/KIOPTRIX LEVEL 1 (1).md
        - Kioptrix Level 1.1 (2): Write-ups/vulnhub/KIOPTRIX LEVEL 1.1 (2).md
        - Kioptrix Level 1.2 (3): Write-ups/vulnhub/KIOPTRIX LEVEL 1.2 (3).md
        - Kioptrix Level 1.3 (4): Write-ups/vulnhub/KIOPTRIX LEVEL 1.3 (4).md
        - Kioptrix 2014 (5): Write-ups/vulnhub/KIOPTRIX 2014 (5).md

# plugin info
plugins:
  # - optimize
  - search
  # - blog


# markdown
markdown_extensions:

  # toc
  - toc:
      permalink: true
  
  # admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # button
  - attr_list
  
  # code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  - tables

  - footnotes
  
  # formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # icons emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


# additional info
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zhsh9

copyright: |
  Copyright &copy; 2023 <a href="https://github.com/zhsh9" target="_blank" rel="noopener">zhsh</a>


# KaTex
extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css